# Import

In [1]:
import pandas as pd
import numpy as np
import os
from tqdm import tqdm

# Load Data

In [2]:
file_dir = 'D:/OneDrive - 연세대학교 (Yonsei University)/Projects/Yonsei_TELab/003_도로상충_210517-/2차년도_2022/07-2_2차년도착수보고_후/03_사고위험구간분석'

In [3]:
accident_file = '사고데이터통합_2018-2020.xlsx'

In [4]:
accident_path = os.path.join(file_dir, accident_file)

In [5]:
accident = pd.read_excel(accident_path, sheet_name = '정렬')

In [6]:
accident.head(3)

,본부,지사,사고일자,월별,사고시간,시간1단위,시간3단위,주야,사고노선,사고발생이정,...,사고후상태\n전복,사고후상태\n화재,사고후상태\n잭나이프,사고후상태\n언더라이드,사고내용,피해액,피해내용,행정구역,타이어관리번호,화재위치코드
0,충북본부,상주지사,20180101,01월,00:44,0~1,0 ~3,야간,중부내륙선,151.1,...,0,0,0,0,사고차량(현대 NF쏘나타) 양평방향 2차로 주행중 음주운전으로 인하여 차량전면으로 ...,0,가드레일 3매\n지주 6본\n블럭아웃 6본\n방초매트 7m\n,경상북도 상주시 사벌면 덕담리,NaN,NaN
1,부산경남본부,양산지사,20180101,01월,03:14,3~4,3 ~6,야간,남해선,15.8,...,0,0,0,0,#1차량 (산타페구형) 양산-부산방향 3차로 주행중 차량우측 전면으로 3차로에 주행...,"1,988,400",가드레일 외 조사중,전남 광양시 광양읍 사곡리,NaN,NaN
2,수도권본부,경기광주지사,20180101,01월,03:39,3~4,3 ~6,야간,제2중부선,331.5,...,0,0,0,0,사고차량 제2중부선 통영방향 2차로 주행 중 포트홀을 발견치 못하고 운전석 앞 타...,0,이상없음,경기 이천시 신둔면 고척리,NaN,NaN

In [7]:
accident.columns

Index(['본부', '지사', '사고일자', '월별', '사고시간', '시간1단위', '시간3단위', '주야', '사고노선',
       '사고발생이정',
       ...
       '사고후상태\n전복', '사고후상태\n화재', '사고후상태\n잭나이프', '사고후상태\n언더라이드', '사고내용', '피해액',
       '피해내용', '행정구역', '타이어관리번호', '화재위치코드'],
      dtype='object', length=117)

# Pivot

In [8]:
pivoted_df = pd.pivot_table(accident,
                         index = ['사고노선', '기종점명', '사고발생이정', '발생지점', '구분'], # 행 위치에 들어갈 열
                         columns = ['차로'], # 열 위치에 들어갈 열
                         values = '사고등급',
                         aggfunc = 'count'
                           ) #데이터 집계함수

In [9]:
pivoted_df

차로                             1/1차로  1/2차로  1/3차로  1/4차로  1/5차로  2/2차로  \
사고노선    기종점명 사고발생이정 발생지점 구분
ㄱ광주대구선  광주   4.60   램프   갓길      NaN    NaN    NaN    NaN    NaN    NaN
                         차로      NaN    NaN    NaN    NaN    NaN    NaN
             4.70   램프   갓길      NaN    NaN    NaN    NaN    NaN    NaN
             4.80   램프   갓길      NaN    NaN    NaN    NaN    NaN    NaN
             6.80   본선   본선차로    NaN    NaN    NaN    NaN    NaN    NaN
...                              ...    ...    ...    ...    ...    ...
호남선의 지선 논산   16.10  본선   본선차로    NaN    1.0    NaN    NaN    NaN    NaN
             44.70  본선   갓길      NaN    NaN    NaN    NaN    NaN    NaN
             49.10  본선   갓길      NaN    NaN    NaN    NaN    NaN    NaN
             34.70  본선   갓길      NaN    NaN    NaN    NaN    NaN    NaN
             36.98  본선   갓길      NaN    NaN    NaN    NaN    NaN    NaN

차로                             2/3차로  2/4차로  2/5차로  3/3차로  ...  4/4차로  4/5차로  \
사고노선    기종점명 사고발생이정 발생지점 구분                                ...
ㄱ광주대구선  광주   4.60   램프   갓길      NaN    NaN    NaN    NaN  ...    NaN    NaN
                         차로      NaN    NaN    NaN    NaN  ...    NaN    NaN
             4.70   램프   갓길      NaN    NaN    NaN    NaN  ...    NaN    NaN
             4.80   램프   갓길      NaN    NaN    NaN    NaN  ...    NaN    NaN
             6.80   본선   본선차로    NaN    NaN    NaN    NaN  ...    NaN    NaN
...                              ...    ...    ...    ...  ...    ...    ...
호남선의 지선 논산   16.10  본선   본선차로    NaN    NaN    NaN    NaN  ...    NaN    NaN
             44.70  본선   갓길      NaN    NaN    NaN    NaN  ...    NaN    NaN
             49.10  본선   갓길      NaN    NaN    NaN    NaN  ...    NaN    NaN
             34.70  본선   갓길      NaN    NaN    NaN    NaN  ...    NaN    NaN
             36.98  본선   갓길      NaN    NaN    NaN    NaN  ...    NaN    NaN

차로                             5/5차로   갓길  기타  다이아몬드형  직결형  클로버형  트럼팻형  혼합형
사고노선    기종점명 사고발생이정 발생지점 구분
ㄱ광주대구선  광주   4.60   램프   갓길      NaN  NaN NaN     NaN  NaN   1.0   1.0  NaN
                         차로      NaN  NaN NaN     NaN  NaN   1.0   NaN  NaN
             4.70   램프   갓길      NaN  NaN NaN     NaN  NaN   NaN   1.0  NaN
             4.80   램프   갓길      NaN  NaN NaN     NaN  NaN   1.0   3.0  NaN
             6.80   본선   본선차로    NaN  1.0 NaN     NaN  NaN   NaN   NaN  NaN
...                              ...  ...  ..     ...  ...   ...   ...  ...
호남선의 지선 논산   16.10  본선   본선차로    NaN  NaN NaN     NaN  NaN   NaN   NaN  NaN
             44.70  본선   갓길      NaN  1.0 NaN     NaN  NaN   NaN   NaN  NaN
             49.10  본선   갓길      NaN  1.0 NaN     NaN  NaN   NaN   NaN  NaN
             34.70  본선   갓길      NaN  1.0 NaN     NaN  NaN   NaN   NaN  NaN
             36.98  본선   갓길      NaN  1.0 NaN     NaN  NaN   NaN   NaN  NaN

[13470 rows x 22 columns]

In [10]:
#pivoted_df.to_csv('test2.csv', encoding = 'cp949')

In [15]:
pivot_df_1 = pd.pivot_table(accident,
                         index = ['발생지점'], # 행 위치에 들어갈 열
                         #columns = ['차로'], # 열 위치에 들어갈 열
                         values = '사고등급',
                         aggfunc = 'count'
                           ) #데이터 집계함수

In [16]:
pivot_df_1

           사고등급
발생지점
TG(TCS)    1978
TG(하이패스)    963
램프         3721
본선        15437
졸음쉼터        168
터널         1046
휴게소         370

In [18]:
pivot_df_1.to_csv('test3.csv', encoding = 'cp949')

In [19]:
pivot_df_2 = pd.pivot_table(accident,
                         index = ['발생지점', '구분'], # 행 위치에 들어갈 열
                         #columns = ['차로'], # 열 위치에 들어갈 열
                         values = '사고등급',
                         aggfunc = 'count'
                           ) #데이터 집계함수

In [20]:
pivot_df_2

                   사고등급
발생지점     구분
TG(TCS)  고속도로진입부    678
         고속도로진출부    697
         본선TG       460
TG(하이패스) 고속도로진입부    260
         고속도로진출부    414
         본선TG       240
램프       갓길        1143
         노즈부        389
         차로        1988
본선       가변차로        48
         가속차로       148
         감속차로        90
         갓길        2379
         교량         139
         노즈부        165
         버스전용차로       1
         본선차로     11476
         비상주차대       12
         정류장(BS)      9
         평면교차로        1
졸음쉼터     가속차로         1
         갓길           2
         내부           1
         본선차로         1
         진입부          1
터널       내부         815
         입구부        113
         출구부         93
휴게소      내부         126
         진입부        189
         진출부         44

In [21]:
pivot_df_2.to_csv('test4.csv', encoding = 'cp949')

In [22]:
pivot_df_3 = pd.pivot_table(accident,
                         index = ['발생지점', '구분', '차로'], # 행 위치에 들어갈 열
                         #columns = ['차로'], # 열 위치에 들어갈 열
                         values = '사고등급',
                         aggfunc = 'count'
                           ) #데이터 집계함수

In [23]:
pivot_df_3

                       사고등급
발생지점    구분      차로
TG(TCS) 고속도로진입부 1/2차로     1
                기타        2
                직결형       1
                클로버형      1
                트럼팻형      1
...                     ...
휴게소     진입부     기타        4
                직결형       4
                트럼팻형      2
        진출부     3/3차로     1
                기타        1

[123 rows x 1 columns]

In [24]:
pivot_df_3.to_csv('test5.csv', encoding = 'cp949')